/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import JAVAS.Conexion;
import JAVAS.Reserva;
import JAVAS.Scooter;
import JAVAS.Usuario;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.MouseInfo;
import java.awt.Point;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author Naga
 */
public class Principal extends javax.swing.JFrame {

    private int x;
    private int y;
    private boolean editar;
    private Usuario usuario;
    private Reserva reserva;
    private Scooter scooter;
    private Connection conn;
    private DefaultTableModel modeloUsuario;
    private DefaultTableModel modeloScooter;
    private DefaultTableModel modeloReserva;
    private ResultSet usuarioList;
    private String separador;
        
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        separador=System.getProperty("file.separator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_informes = new javax.swing.ButtonGroup();
        Main = new javax.swing.JPanel();
        Head = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        marca = new javax.swing.JLabel();
        jLabel_cerrar = new javax.swing.JLabel();
        jLabel_minimizar = new javax.swing.JLabel();
        jLabel_clientes = new javax.swing.JLabel();
        jLabel_scooters = new javax.swing.JLabel();
        jLabel_reservas = new javax.swing.JLabel();
        jLabel_informes = new javax.swing.JLabel();
        jLabel_conexion = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        jPanel_conexion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_user = new javax.swing.JTextField();
        jTextField_pass = new javax.swing.JTextField();
        jLabel_conectar = new javax.swing.JLabel();
        jLabel_desconectar = new javax.swing.JLabel();
        jPanel_clientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_clientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel_clientes_add = new javax.swing.JLabel();
        jLabel_clientes_edit = new javax.swing.JLabel();
        jLabel_clientes_delete = new javax.swing.JLabel();
        jPanel_scooters = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_scooter = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel_scooter_add = new javax.swing.JLabel();
        jLabel_scooter_edit = new javax.swing.JLabel();
        jLabel_scooter_delete = new javax.swing.JLabel();
        jPanel_prestamos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_prestamos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel_prestamos_add = new javax.swing.JLabel();
        jLabel_prestamos_edit = new javax.swing.JLabel();
        jLabel_prestamos_delete = new javax.swing.JLabel();
        jPanel_informes = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_incormes_create = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton_horas = new javax.swing.JRadioButton();
        jRadioButton_ciudad = new javax.swing.JRadioButton();
        jRadioButton_usuario = new javax.swing.JRadioButton();
        jComboBox_ciudad = new javax.swing.JComboBox<>();
        jComboBox_usuario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(802, 602));
        setMinimumSize(new java.awt.Dimension(802, 602));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(802, 602));
        setResizable(false);

        Main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 165, 245)));
        Main.setMaximumSize(new java.awt.Dimension(800, 600));
        Main.setMinimumSize(new java.awt.Dimension(800, 600));
        Main.setPreferredSize(new java.awt.Dimension(800, 600));

        Head.setBackground(new java.awt.Color(66, 165, 245));
        Head.setMaximumSize(new java.awt.Dimension(800, 200));
        Head.setMinimumSize(new java.awt.Dimension(800, 200));
        Head.setPreferredSize(new java.awt.Dimension(800, 200));
        Head.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeadMouseDragged(evt);
            }
        });
        Head.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeadMousePressed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Varios/scooter.png"))); // NOI18N

        marca.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        marca.setText("ScooTing");

        jLabel_cerrar.setBackground(new java.awt.Color(13, 71, 161));
        jLabel_cerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_cerrar.setText("X");
        jLabel_cerrar.setOpaque(true);
        jLabel_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_cerrarMouseClicked(evt);
            }
        });

        jLabel_minimizar.setBackground(new java.awt.Color(13, 71, 161));
        jLabel_minimizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_minimizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimizar.setText("_");
        jLabel_minimizar.setOpaque(true);
        jLabel_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizarMouseClicked(evt);
            }
        });

        jLabel_clientes.setBackground(new java.awt.Color(66, 165, 245));
        jLabel_clientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_clientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_clientes.setText("Clientes");
        jLabel_clientes.setEnabled(false);
        jLabel_clientes.setOpaque(true);
        jLabel_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_clientesMouseClicked(evt);
            }
        });

        jLabel_scooters.setBackground(new java.awt.Color(66, 165, 245));
        jLabel_scooters.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_scooters.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_scooters.setText("Scooters");
        jLabel_scooters.setEnabled(false);
        jLabel_scooters.setOpaque(true);
        jLabel_scooters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_scootersMouseClicked(evt);
            }
        });

        jLabel_reservas.setBackground(new java.awt.Color(66, 165, 245));
        jLabel_reservas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_reservas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_reservas.setText("Reservas");
        jLabel_reservas.setEnabled(false);
        jLabel_reservas.setOpaque(true);
        jLabel_reservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_reservasMouseClicked(evt);
            }
        });

        jLabel_informes.setBackground(new java.awt.Color(66, 165, 245));
        jLabel_informes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_informes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_informes.setText("Informes");
        jLabel_informes.setEnabled(false);
        jLabel_informes.setOpaque(true);
        jLabel_informes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_informesMouseClicked(evt);
            }
        });

        jLabel_conexion.setBackground(new java.awt.Color(13, 71, 161));
        jLabel_conexion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_conexion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_conexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_conexion.setText("Conexión");
        jLabel_conexion.setOpaque(true);
        jLabel_conexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_conexionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(logo)
                .addGap(21, 21, 21)
                .addGroup(HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeadLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HeadLayout.createSequentialGroup()
                        .addComponent(marca)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jLabel_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel_scooters, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel_reservas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel_informes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addGroup(HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(marca)
                    .addComponent(logo))
                .addGap(20, 20, 20)
                .addGroup(HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel_scooters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_reservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_informes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_conexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Body.setBackground(new java.awt.Color(255, 255, 255));
        Body.setMaximumSize(new java.awt.Dimension(800, 400));
        Body.setMinimumSize(new java.awt.Dimension(800, 400));
        Body.setPreferredSize(new java.awt.Dimension(800, 400));
        Body.setLayout(new java.awt.CardLayout());

        jPanel_conexion.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_conexion.setMaximumSize(new java.awt.Dimension(800, 400));
        jPanel_conexion.setMinimumSize(new java.awt.Dimension(800, 400));
        jPanel_conexion.setPreferredSize(new java.awt.Dimension(800, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Contraseña:");

        jTextField_user.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_user.setText("root");

        jTextField_pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel_conectar.setBackground(new java.awt.Color(241, 196, 15));
        jLabel_conectar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_conectar.setForeground(new java.awt.Color(13, 71, 161));
        jLabel_conectar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_conectar.setText("Conectar");
        jLabel_conectar.setMaximumSize(new java.awt.Dimension(114, 22));
        jLabel_conectar.setMinimumSize(new java.awt.Dimension(114, 22));
        jLabel_conectar.setOpaque(true);
        jLabel_conectar.setPreferredSize(new java.awt.Dimension(114, 22));
        jLabel_conectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_conectarMouseClicked(evt);
            }
        });

        jLabel_desconectar.setBackground(new java.awt.Color(241, 196, 15));
        jLabel_desconectar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_desconectar.setForeground(new java.awt.Color(13, 71, 161));
        jLabel_desconectar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_desconectar.setText("Desconectar");
        jLabel_desconectar.setOpaque(true);
        jLabel_desconectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_desconectarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_conexionLayout = new javax.swing.GroupLayout(jPanel_conexion);
        jPanel_conexion.setLayout(jPanel_conexionLayout);
        jPanel_conexionLayout.setHorizontalGroup(
            jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_conexionLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel_conexionLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(jTextField_user, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_conexionLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(jTextField_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_conexionLayout.createSequentialGroup()
                        .addComponent(jLabel_conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(jLabel_desconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel_conexionLayout.setVerticalGroup(
            jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_conexionLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_desconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        Body.add(jPanel_conexion, "card2");

        jPanel_clientes.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_clientes.setMaximumSize(new java.awt.Dimension(800, 400));
        jPanel_clientes.setMinimumSize(new java.awt.Dimension(800, 400));
        jPanel_clientes.setPreferredSize(new java.awt.Dimension(800, 400));

        jScrollPane1.setBorder(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(458, 375));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(458, 375));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(458, 375));

        jTable_clientes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_clientes.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_clientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable_clientes);

        jPanel1.setBackground(new java.awt.Color(66, 165, 245));

        jLabel_clientes_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Varios/add.png"))); // NOI18N
        jLabel_clientes_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_clientes_addMouseClicked(evt);
            }
        });

        jLabel_clientes_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Varios/edit.png"))); // NOI18N
        jLabel_clientes_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_clientes_editMouseClicked(evt);
            }
        });

        jLabel_clientes_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Varios/delete.png"))); // NOI18N
        jLabel_clientes_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_clientes_deleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_clientes_add, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_clientes_edit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_clientes_delete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_clientes_add)
                .addGap(20, 20, 20)
                .addComponent(jLabel_clientes_edit)
                .addGap(40, 40, 40)
                .addComponent(jLabel_clientes_delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_clientesLayout = new javax.swing.GroupLayout(jPanel_clientes);
        jPanel_clientes.setLayout(jPanel_clientesLayout);
        jPanel_clientesLayout.setHorizontalGroup(
            jPanel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_clientesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel_clientesLayout.setVerticalGroup(
            jPanel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Body.add(jPanel_clientes, "card3");

        jPanel_scooters.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_scooters.setMaximumSize(new java.awt.Dimension(800, 400));
        jPanel_scooters.setMinimumSize(new java.awt.Dimension(800, 400));
        jPanel_scooters.setPreferredSize(new java.awt.Dimension(800, 400));

        jScrollPane3.setBorder(null);
        jScrollPane3.setMaximumSize(new java.awt.Dimension(458, 375));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(458, 375));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(458, 375));

        jTable_scooter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable_scooter);

        jPanel3.setBackground(new java.awt.Color(66, 165, 245));

        jLabel_scooter_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Varios/add.png"))); // NOI18N
        jLabel_scooter_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_scooter_addMouseClicked(evt);
            }
        });

        jLabel_scooter_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Varios/edit.png"))); // NOI18N
        jLabel_scooter_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_scooter_editMouseClicked(evt);
            }
        });

        jLabel_scooter_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Varios/delete.png"))); // NOI18N
        jLabel_scooter_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_scooter_deleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_scooter_add, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_scooter_edit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_scooter_delete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_scooter_add)
                .addGap(20, 20, 20)
                .addComponent(jLabel_scooter_edit)
                .addGap(40, 40, 40)
                .addComponent(jLabel_scooter_delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_scootersLayout = new javax.swing.GroupLayout(jPanel_scooters);
        jPanel_scooters.setLayout(jPanel_scootersLayout);
        jPanel_scootersLayout.setHorizontalGroup(
            jPanel_scootersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_scootersLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_scootersLayout.setVerticalGroup(
            jPanel_scootersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Body.add(jPanel_scooters, "card5");

        jPanel_prestamos.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_prestamos.setMaximumSize(new java.awt.Dimension(800, 400));
        jPanel_prestamos.setMinimumSize(new java.awt.Dimension(800, 400));
        jPanel_prestamos.setPreferredSize(new java.awt.Dimension(800, 400));

        jScrollPane2.setBorder(null);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(458, 375));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(458, 375));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(458, 375));

        jTable_prestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_prestamos);

        jPanel2.setBackground(new java.awt.Color(66, 165, 245));

        jLabel_prestamos_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Varios/add.png"))); // NOI18N
        jLabel_prestamos_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_prestamos_addMouseClicked(evt);
            }
        });

        jLabel_prestamos_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Varios/edit.png"))); // NOI18N
        jLabel_prestamos_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_prestamos_editMouseClicked(evt);
            }
        });

        jLabel_prestamos_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Varios/delete.png"))); // NOI18N
        jLabel_prestamos_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_prestamos_deleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_prestamos_add, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_prestamos_edit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_prestamos_delete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_prestamos_add)
                .addGap(20, 20, 20)
                .addComponent(jLabel_prestamos_edit)
                .addGap(40, 40, 40)
                .addComponent(jLabel_prestamos_delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_prestamosLayout = new javax.swing.GroupLayout(jPanel_prestamos);
        jPanel_prestamos.setLayout(jPanel_prestamosLayout);
        jPanel_prestamosLayout.setHorizontalGroup(
            jPanel_prestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_prestamosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_prestamosLayout.setVerticalGroup(
            jPanel_prestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        Body.add(jPanel_prestamos, "card4");

        jPanel_informes.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_informes.setMaximumSize(new java.awt.Dimension(800, 400));
        jPanel_informes.setMinimumSize(new java.awt.Dimension(800, 400));
        jPanel_informes.setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel4.setBackground(new java.awt.Color(66, 165, 245));

        jLabel_incormes_create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Varios/add.png"))); // NOI18N
        jLabel_incormes_create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_incormes_createMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_incormes_create)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_incormes_create)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Generar informes por:");

        buttonGroup_informes.add(jRadioButton_horas);
        jRadioButton_horas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_horas.setSelected(true);
        jRadioButton_horas.setText(" Alquiler por horas");
        jRadioButton_horas.setBorder(null);
        jRadioButton_horas.setOpaque(false);

        buttonGroup_informes.add(jRadioButton_ciudad);
        jRadioButton_ciudad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_ciudad.setText(" Usuarios por ciudad");
        jRadioButton_ciudad.setBorder(null);
        jRadioButton_ciudad.setOpaque(false);

        buttonGroup_informes.add(jRadioButton_usuario);
        jRadioButton_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_usuario.setText("Alquileres de usuario");
        jRadioButton_usuario.setBorder(null);
        jRadioButton_usuario.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_horas)
                    .addComponent(jLabel3)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_usuario)
                            .addComponent(jRadioButton_ciudad))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(jRadioButton_horas)
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_ciudad)
                    .addComponent(jComboBox_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_usuario)
                    .addComponent(jComboBox_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_informesLayout = new javax.swing.GroupLayout(jPanel_informes);
        jPanel_informes.setLayout(jPanel_informesLayout);
        jPanel_informesLayout.setHorizontalGroup(
            jPanel_informesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_informesLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_informesLayout.setVerticalGroup(
            jPanel_informesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Body.add(jPanel_informes, "card6");

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Body, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 734, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 553, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //metodo para cerrar
    private void jLabel_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cerrarMouseClicked
        try {
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jLabel_cerrarMouseClicked

    //metodo para minimizar
    private void jLabel_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizarMouseClicked
        setVisible(true);
        setExtendedState(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_minimizarMouseClicked

    //metodos para arrastrar la ventana
    private void HeadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeadMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_HeadMousePressed

    private void HeadMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeadMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_HeadMouseDragged

    //metodos de gestion de los botones de la cabecera
    private void jLabel_conexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_conexionMouseClicked
        JLabel[] label={jLabel_clientes,jLabel_scooters,jLabel_reservas,jLabel_informes};
        JPanel[] panel={jPanel_clientes,jPanel_scooters,jPanel_prestamos,jPanel_informes};
        setLblColor(jLabel_conexion, jPanel_conexion);
        resetLblColor(label, panel);
    }//GEN-LAST:event_jLabel_conexionMouseClicked

    private void jLabel_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_clientesMouseClicked
        JLabel[] label={jLabel_conexion,jLabel_scooters,jLabel_reservas,jLabel_informes};
        JPanel[] panel={jPanel_conexion,jPanel_scooters,jPanel_prestamos,jPanel_informes};
        setLblColor(jLabel_clientes, jPanel_clientes);
        resetLblColor(label, panel);
        rellenaUsuarios();
    }//GEN-LAST:event_jLabel_clientesMouseClicked

    private void jLabel_scootersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_scootersMouseClicked
        JLabel[] label={jLabel_conexion,jLabel_clientes,jLabel_reservas,jLabel_informes};
        JPanel[] panel={jPanel_conexion,jPanel_clientes,jPanel_prestamos,jPanel_informes};
        setLblColor(jLabel_scooters, jPanel_scooters);
        resetLblColor(label, panel);
        rellenaScooters();
    }//GEN-LAST:event_jLabel_scootersMouseClicked

    private void jLabel_reservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_reservasMouseClicked
        JLabel[] label={jLabel_conexion,jLabel_clientes,jLabel_scooters,jLabel_informes};
        JPanel[] panel={jPanel_conexion,jPanel_clientes,jPanel_scooters,jPanel_informes};
        setLblColor(jLabel_reservas, jPanel_prestamos);
        resetLblColor(label, panel);
        rellenaReservas();
    }//GEN-LAST:event_jLabel_reservasMouseClicked

    private void jLabel_informesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_informesMouseClicked
        JLabel[] label={jLabel_conexion,jLabel_clientes,jLabel_scooters,jLabel_reservas};
        JPanel[] panel={jPanel_conexion,jPanel_clientes,jPanel_scooters,jPanel_prestamos};
        setLblColor(jLabel_informes, jPanel_informes);
        resetLblColor(label, panel);
        rellenaCiudadesCombo();
        rellenaUsuariosCombo();
    }//GEN-LAST:event_jLabel_informesMouseClicked

    //metodos para cambiar el color de las pestañas dependiendo de si esta seleccionada o no
    private void setLblColor(JLabel lbl,JPanel panel){
        lbl.setBackground(new Color(13,71,161));
        lbl.setForeground(Color.white);
        panel.setVisible(true);
    }
    
    private void resetLblColor(JLabel[] label,JPanel[] panel){
        for(JLabel lbl:label){
            lbl.setBackground(new Color(66,165,245));
            lbl.setForeground(Color.black);
        }
        for(JPanel p:panel){
            p.setVisible(false);
        }
    }
    
    //conectarse y desconectarse
    private void jLabel_conectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_conectarMouseClicked
        String usuario=jTextField_user.getText();
        String pass=jTextField_pass.getText();
        if(usuario.length()>0){
            Conexion conexion=new Conexion();
            conn=conexion.conectar(usuario,pass);
            if(conn==null){
                aviso("Conexion no establecida");
            }
            else{
                aviso("Conexion establecida");
                JLabel[] label={jLabel_clientes,jLabel_scooters,jLabel_reservas,jLabel_informes};
                for(JLabel j:label){
                    j.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_jLabel_conectarMouseClicked

    private void jLabel_desconectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_desconectarMouseClicked
        try {
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        aviso("Conexion desactivada");
        JLabel[] label={jLabel_clientes,jLabel_scooters,jLabel_reservas,jLabel_informes};
        for(JLabel j:label){
            j.setEnabled(false);
        }
    }//GEN-LAST:event_jLabel_desconectarMouseClicked

    //metodos gestion clientes
    private void jLabel_clientes_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_clientes_addMouseClicked
        Cliente cliente=new Cliente(this,true);
        cliente.setVisible(true);
        rellenaUsuarios();
    }//GEN-LAST:event_jLabel_clientes_addMouseClicked

    private void jLabel_clientes_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_clientes_editMouseClicked
        try{
            //obtenemos el cliente
            int fila=jTable_clientes.getSelectedRow();
            int id=(Integer) (modeloUsuario.getValueAt(fila, 0));
            String nombre=(String)(modeloUsuario.getValueAt(fila,1));
            String apellidos=(String)(modeloUsuario.getValueAt(fila,2));
            String dni=(String)(modeloUsuario.getValueAt(fila,3));
            String direccion=(String)(modeloUsuario.getValueAt(fila,4));
            String ciudad=(String)(modeloUsuario.getValueAt(fila,5));
            String telefono=(String)(modeloUsuario.getValueAt(fila,6));
            this.usuario=new Usuario(id,nombre,apellidos,dni,direccion,ciudad,telefono);
            
            editar=true;
            Cliente cliente=new Cliente(this,true);
            cliente.setVisible(true);
            rellenaUsuarios();
            editar=false;
        }
        catch(Exception e){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_jLabel_clientes_editMouseClicked

    private void jLabel_clientes_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_clientes_deleteMouseClicked
        try{
            //obtenemos el id a borrar
            int fila=jTable_clientes.getSelectedRow();
            int id=(Integer)(modeloUsuario.getValueAt(fila,0));
            try {
                //sql
                PreparedStatement ps=conn.prepareStatement("DELETE FROM cliente WHERE id=?");
                ps.setInt(1,id);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            rellenaUsuarios();
        }
        catch(Exception e){
            aviso("Ninguna fila seleccionada");
        }
        rellenaUsuarios();
    }//GEN-LAST:event_jLabel_clientes_deleteMouseClicked

    //rellenar tabla de usuarios
    private void rellenaUsuarios(){
        try {
            //modelo
            modeloUsuario=new DefaultTableModel();
            jTable_clientes.setModel(modeloUsuario);
            modeloUsuario.addColumn("Id");
            modeloUsuario.addColumn("Nombre");
            modeloUsuario.addColumn("Apellidos");
            modeloUsuario.addColumn("DNI");
            modeloUsuario.addColumn("Direccion");
            modeloUsuario.addColumn("Ciudad");
            modeloUsuario.addColumn("Telefono");

            //consulta
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("SELECT id,nombre,apellidos,dni,direccion,ciudad,telefono FROM cliente");
            while(rs.next()){
                Object[] fila = new Object[7];
                for (int i = 0; i < 7; i++) {
                    fila[i]=rs.getObject(i+1);
                }
                modeloUsuario.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //metodos gestion scooters
    private void jLabel_scooter_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_scooter_addMouseClicked
        Scooters scooters=new Scooters(this,true);
        scooters.setVisible(true);
        rellenaScooters();
    }//GEN-LAST:event_jLabel_scooter_addMouseClicked

    private void jLabel_scooter_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_scooter_editMouseClicked
        try{
            //obtenemos el cliente
            int fila=jTable_scooter.getSelectedRow();
            int id=(Integer) (modeloScooter.getValueAt(fila, 0));
            String modelo=(String)(modeloScooter.getValueAt(fila,1));
            String cilindrada=(String)(modeloScooter.getValueAt(fila,2));
            this.scooter=new Scooter(id,modelo,cilindrada);
            
            editar=true;
            Scooters scooters=new Scooters(this,true);
            scooters.setVisible(true);
            rellenaScooters();
            editar=false;
        }
        catch(Exception e){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_jLabel_scooter_editMouseClicked

    private void jLabel_scooter_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_scooter_deleteMouseClicked
        try{
            //obtenemos el id a borrar
            int fila=jTable_scooter.getSelectedRow();
            int id=(Integer)(modeloScooter.getValueAt(fila,0));
            try {
                //sql
                PreparedStatement ps=conn.prepareStatement("DELETE FROM scooter WHERE id=?");
                ps.setInt(1,id);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            rellenaScooters();
        }
        catch(Exception e){
            aviso("Ninguna fila seleccionada");
        }
    }//GEN-LAST:event_jLabel_scooter_deleteMouseClicked

    //rellenamos la tabla scooter
    private void rellenaScooters(){
        try {
            //modelo
            modeloScooter=new DefaultTableModel();
            jTable_scooter.setModel(modeloScooter);
            modeloScooter.addColumn("Id");
            modeloScooter.addColumn("Modelo");
            modeloScooter.addColumn("Cilindrada");

            //consulta
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("SELECT id,modelo,cilindrada FROM scooter");
            while(rs.next()){
                Object[] fila = new Object[3];
                for (int i = 0; i < 3; i++) {
                    fila[i]=rs.getObject(i+1);
                }
                modeloScooter.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //metodos gestion prestamos
    private void jLabel_prestamos_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_prestamos_addMouseClicked
        Reservas reservas=new Reservas(this,true);
        reservas.setVisible(true);
        rellenaReservas();
    }//GEN-LAST:event_jLabel_prestamos_addMouseClicked

    private void jLabel_prestamos_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_prestamos_editMouseClicked
        try{
            //obtenemos el cliente
            int fila=jTable_prestamos.getSelectedRow();
            int id=(Integer) (modeloReserva.getValueAt(fila, 0));
            int id_usuario=(Integer) (modeloReserva.getValueAt(fila, 1));
            int id_scooter=(Integer) (modeloReserva.getValueAt(fila, 2));
            Date dia=(Date) (modeloReserva.getValueAt(fila, 3));
            int hora_inicio=(Integer) (modeloReserva.getValueAt(fila, 4));
            int hora_fin=(Integer) (modeloReserva.getValueAt(fila, 5));
            this.reserva=new Reserva(id,id_usuario,id_scooter,dia,hora_inicio,hora_fin);
            
            editar=true;
            Reservas reservas=new Reservas(this,true);
            reservas.setVisible(true);
            rellenaReservas();
            editar=false;
        }
        catch(Exception e){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_jLabel_prestamos_editMouseClicked

    private void jLabel_prestamos_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_prestamos_deleteMouseClicked
        try{
            //obtenemos el id a borrar
            int fila=jTable_prestamos.getSelectedRow();
            int id=(Integer)(modeloReserva.getValueAt(fila,0));
            try {
                //sql
                PreparedStatement ps=conn.prepareStatement("DELETE FROM reserva WHERE id=?");
                ps.setInt(1,id);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            rellenaReservas();
        }
        catch(Exception e){
            aviso("Ninguna fila seleccionada");
        }

    }//GEN-LAST:event_jLabel_prestamos_deleteMouseClicked

    //rellena reservas
    private void rellenaReservas(){
        try {
            //modelo
            modeloReserva=new DefaultTableModel();
            jTable_prestamos.setModel(modeloReserva);
            modeloReserva.addColumn("Id");
            modeloReserva.addColumn("Usuario");
            modeloReserva.addColumn("Scooter");
            modeloReserva.addColumn("Dia");
            modeloReserva.addColumn("Hora de inicio");
            modeloReserva.addColumn("Hora de fin");

            //consulta
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("SELECT id,id_usuario,id_scooter,dia,hora_inicio,hora_fin FROM reserva");
            while(rs.next()){
                Object[] fila = new Object[6];
                for (int i = 0; i < 6; i++) {
                    fila[i]=rs.getObject(i+1);
                }
                modeloReserva.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //metodo creacion informes
    private void jLabel_incormes_createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_incormes_createMouseClicked
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter","root","");
            
            Map parameters=new HashMap();
            JasperPrint print=null;
            String informe=null;
            String archivo=null;
            if(jRadioButton_horas.isSelected()){
                informe="informes"+separador+"informe+graficos-horas.jasper";
                archivo="informes"+separador+"horas.pdf";
            }
            else if(jRadioButton_ciudad.isSelected()){
                parameters.put("CIUDAD",jComboBox_ciudad.getSelectedItem());
                informe="informes"+separador+"informe+variable-ciudad.jasper";
                archivo="informes"+separador+"ciudad.pdf";
            }
            else{
                parameters.put("ID_CLIENTE",getId(jComboBox_usuario, usuarioList));
                informe="informes"+separador+"informe+subinforme-usuario+todos sus alquileres.jasper";
                archivo="informes"+separador+"cliente.pdf";
            }
            print=JasperFillManager.fillReport(informe,parameters,conn);
            JasperExportManager.exportReportToPdfFile(print,archivo);
            aviso("Informe creado");
            
            //abrimos el pdf
            try {
                 File path = new File (archivo);
                 Desktop.getDesktop().open(path);
            }catch (IOException ex) {
                 ex.printStackTrace();
            }
        }
        catch(Throwable e){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jLabel_incormes_createMouseClicked

    //rellena usuarios
    private void rellenaUsuariosCombo(){
        try {
            //consulta
            Statement st=conn.createStatement();
            usuarioList=st.executeQuery("SELECT id,nombre,apellidos,dni FROM cliente");
            while(usuarioList.next()){
                Object[] fila = new Object[4];
                for (int i = 0; i < 4; i++) {
                    fila[i]=usuarioList.getObject(i+1);
                }
                jComboBox_usuario.addItem(fila[1]+" "+fila[2]+" "+fila[3]);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Reservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //Rellena ciudades
    private void rellenaCiudadesCombo(){
        try {
            //consulta
            Statement st=conn.createStatement();
            ResultSet ciudadList=st.executeQuery("SELECT DISTINCT ciudad FROM cliente");
            while(ciudadList.next()){
                jComboBox_ciudad.addItem(ciudadList.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Reservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //obtenemos el id del elemento elegido en el combobox
    private int getId(JComboBox combo,ResultSet rs){
        int id=-1;
        String seleccion=combo.getSelectedItem().toString();
        //buscamos los nombres de producto en el resultser
        try {
            rs.beforeFirst();
            while(rs.next()){
                String currentElement=rs.getString(2)+" "+rs.getString(3)+" "+rs.getString(4);
                
                //si coinciden, ponemos la marca
                if(seleccion.equals(currentElement)){
                    id=rs.getInt(1);
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Reservas.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    
    //lanza aviso
    private void aviso(String texto){
        Aviso aviso=new Aviso(Principal.this,true);
        aviso.setAviso(texto);
        aviso.setVisible(true);
    }

    //metodos de compartir info con los jdialog
    public Connection getConn() {
        return conn;
    }
    
    public boolean getEditar(){
        return editar;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public Scooter getScooter() {
        return scooter;
    }

    public Reserva getReserva() {
        return reserva;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Head;
    private javax.swing.JPanel Main;
    private javax.swing.ButtonGroup buttonGroup_informes;
    private javax.swing.JComboBox<String> jComboBox_ciudad;
    private javax.swing.JComboBox<String> jComboBox_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_cerrar;
    private javax.swing.JLabel jLabel_clientes;
    private javax.swing.JLabel jLabel_clientes_add;
    private javax.swing.JLabel jLabel_clientes_delete;
    private javax.swing.JLabel jLabel_clientes_edit;
    private javax.swing.JLabel jLabel_conectar;
    private javax.swing.JLabel jLabel_conexion;
    private javax.swing.JLabel jLabel_desconectar;
    private javax.swing.JLabel jLabel_incormes_create;
    private javax.swing.JLabel jLabel_informes;
    private javax.swing.JLabel jLabel_minimizar;
    private javax.swing.JLabel jLabel_prestamos_add;
    private javax.swing.JLabel jLabel_prestamos_delete;
    private javax.swing.JLabel jLabel_prestamos_edit;
    private javax.swing.JLabel jLabel_reservas;
    private javax.swing.JLabel jLabel_scooter_add;
    private javax.swing.JLabel jLabel_scooter_delete;
    private javax.swing.JLabel jLabel_scooter_edit;
    private javax.swing.JLabel jLabel_scooters;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_clientes;
    private javax.swing.JPanel jPanel_conexion;
    private javax.swing.JPanel jPanel_informes;
    private javax.swing.JPanel jPanel_prestamos;
    private javax.swing.JPanel jPanel_scooters;
    private javax.swing.JRadioButton jRadioButton_ciudad;
    private javax.swing.JRadioButton jRadioButton_horas;
    private javax.swing.JRadioButton jRadioButton_usuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_clientes;
    private javax.swing.JTable jTable_prestamos;
    private javax.swing.JTable jTable_scooter;
    private javax.swing.JTextField jTextField_pass;
    private javax.swing.JTextField jTextField_user;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel marca;
    // End of variables declaration//GEN-END:variables
}
