/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import JAVAS.Reserva;
import java.awt.MouseInfo;
import java.awt.Point;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JSpinner;

/**
 *
 * @author Naga
 */
public class Reservas extends javax.swing.JDialog {

    private int x;
    private int y;
    private boolean editar;
    private Reserva reservas=null;
    Connection conn;
    Principal p;
    ResultSet usuario;
    ResultSet scooter;
    /**
     * Creates new form Reserva
     */
    public Reservas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.p=(Principal)parent;
        this.conn=p.getConn();
        this.editar=p.getEditar();
        rellenaUsuarios();
        rellenaScooters();
        rellenaHoraInicio();
        if(editar){
            this.reservas=p.getReserva();
            rellenaCampos();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_body = new javax.swing.JPanel();
        jLabel_ok = new javax.swing.JLabel();
        jLabel_cancel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_usuario = new javax.swing.JComboBox<>();
        jComboBox_scooter = new javax.swing.JComboBox<>();
        jSpinner_dia = new javax.swing.JSpinner();
        jComboBox_inicio = new javax.swing.JComboBox<>();
        jSpinner_horas = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(305, 390));
        setMinimumSize(new java.awt.Dimension(305, 390));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(305, 390));
        setResizable(false);

        jPanel_head.setBackground(new java.awt.Color(66, 165, 245));
        jPanel_head.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_headMouseDragged(evt);
            }
        });
        jPanel_head.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_headMousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(241, 196, 15));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(13, 71, 161));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reservas");
        jLabel1.setMaximumSize(new java.awt.Dimension(114, 22));
        jLabel1.setMinimumSize(new java.awt.Dimension(114, 22));
        jLabel1.setPreferredSize(new java.awt.Dimension(114, 22));

        javax.swing.GroupLayout jPanel_headLayout = new javax.swing.GroupLayout(jPanel_head);
        jPanel_head.setLayout(jPanel_headLayout);
        jPanel_headLayout.setHorizontalGroup(
            jPanel_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_headLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_headLayout.setVerticalGroup(
            jPanel_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel_body.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_body.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 165, 245)));

        jLabel_ok.setBackground(new java.awt.Color(241, 196, 15));
        jLabel_ok.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_ok.setForeground(new java.awt.Color(13, 71, 161));
        jLabel_ok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ok.setText("Aceptar");
        jLabel_ok.setMaximumSize(new java.awt.Dimension(114, 22));
        jLabel_ok.setMinimumSize(new java.awt.Dimension(114, 22));
        jLabel_ok.setOpaque(true);
        jLabel_ok.setPreferredSize(new java.awt.Dimension(114, 22));
        jLabel_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_okMouseClicked(evt);
            }
        });

        jLabel_cancel.setBackground(new java.awt.Color(241, 196, 15));
        jLabel_cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_cancel.setForeground(new java.awt.Color(13, 71, 161));
        jLabel_cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_cancel.setText("Cancelar");
        jLabel_cancel.setMaximumSize(new java.awt.Dimension(114, 22));
        jLabel_cancel.setMinimumSize(new java.awt.Dimension(114, 22));
        jLabel_cancel.setOpaque(true);
        jLabel_cancel.setPreferredSize(new java.awt.Dimension(114, 22));
        jLabel_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_cancelMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Scooter:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Dia:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Hora inicio:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Horas alquiladas:");

        jSpinner_dia.setModel(new javax.swing.SpinnerDateModel());

        jSpinner_horas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));

        javax.swing.GroupLayout jPanel_bodyLayout = new javax.swing.GroupLayout(jPanel_body);
        jPanel_body.setLayout(jPanel_bodyLayout);
        jPanel_bodyLayout.setHorizontalGroup(
            jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bodyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_bodyLayout.createSequentialGroup()
                        .addComponent(jLabel_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_bodyLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_bodyLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_bodyLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox_scooter, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_bodyLayout.createSequentialGroup()
                        .addGroup(jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinner_horas)
                            .addComponent(jComboBox_inicio, 0, 163, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        jPanel_bodyLayout.setVerticalGroup(
            jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_bodyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_scooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner_horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_headMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jPanel_headMouseDragged

    private void jPanel_headMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel_headMousePressed

    private void jLabel_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_okMouseClicked
        //obtenemos los datos
        int id_usuario=getId(jComboBox_usuario, usuario, "usuario");
        int id_scooter=getId(jComboBox_scooter, scooter, "scooter");
        String dia=getFecha(jSpinner_dia);
        int hora_inicio=Integer.parseInt((String) jComboBox_inicio.getSelectedItem());
        int hora_fin=(int) jSpinner_horas.getValue();
        
        if(hora_inicio+hora_fin>20){
            aviso("No se puede tener en alquiler mas tarde de las 20h");
        }
        else{
            //insertamos
            try {
                PreparedStatement ps=null;
                if(editar){
                    ps=conn.prepareStatement("UPDATE reserva SET id_usuario=?,id_scooter=?,dia=?,"
                            + "hora_inicio=?,hora_fin=? WHERE id="+reservas.getId());
                }
                else{
                    ps=conn.prepareStatement("INSERT INTO reserva(id_usuario,id_scooter,dia,hora_inicio,hora_fin) "
                            + "VALUES(?,?,?,?,?)");
                }
                ps.setInt(1,id_usuario);
                ps.setInt(2,id_scooter);
                ps.setString(3,dia);
                ps.setInt(4,hora_inicio);
                ps.setInt(5,hora_fin);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Reservas.class.getName()).log(Level.SEVERE, null, ex);
            }   
            dispose();
        }
        
    }//GEN-LAST:event_jLabel_okMouseClicked

    private void jLabel_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cancelMouseClicked
        dispose();
    }//GEN-LAST:event_jLabel_cancelMouseClicked

    //rellenamos los campos
    private void rellenaCampos() {
        setElement(jComboBox_usuario,reservas.getId_usuario(),"usuario");
        setElement(jComboBox_scooter, reservas.getId_scooter(), "scooter");
        jSpinner_dia.setValue(reservas.getDia());
        jComboBox_inicio.setSelectedItem(reservas.getHora_inicio());
        jSpinner_horas.setValue(reservas.getHora_fin());
    }
    
    private void rellenaUsuarios() {
        try {
            //consulta
            Statement st=conn.createStatement();
            usuario=st.executeQuery("SELECT id,nombre,apellidos,dni FROM cliente");
            while(usuario.next()){
                Object[] fila = new Object[4];
                for (int i = 0; i < 4; i++) {
                    fila[i]=usuario.getObject(i+1);
                }
                jComboBox_usuario.addItem(fila[1]+" "+fila[2]+" "+fila[3]);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Reservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void rellenaScooters() {
        try {
            //consulta
            Statement st=conn.createStatement();
            scooter=st.executeQuery("SELECT id,modelo,cilindrada FROM scooter");
            while(scooter.next()){
                Object[] fila = new Object[3];
                for (int i = 0; i < 3; i++) {
                    fila[i]=scooter.getObject(i+1);
                }
                jComboBox_scooter.addItem(fila[1]+" "+fila[2]);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Reservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void rellenaHoraInicio() {
        for(int i=8;i<20;i++){
            jComboBox_inicio.addItem(Integer.toString(i));
        }
    }
    
    //obtenemos la fecha del spinner
    private String getFecha(JSpinner spinner){
        String fecha="";
        Date dia=(Date) spinner.getValue();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        fecha = sdf.format(dia);
        return fecha;
    }
    
    //a partir del id, rellenamos el campo correspondiente para que no aparezca el numero
    private void setElement(JComboBox combo,int id,String campo){
        try {
            //consulta
            Statement st=st=conn.createStatement();
            ResultSet rs;
            String cadena;
            if(campo.equals("usuario")){
                rs=st.executeQuery("SELECT nombre,apellidos,dni FROM cliente WHERE id="+id);
                rs.next();
                cadena=rs.getString(1)+" "+rs.getString(2)+" "+rs.getString(3);
            }
            else{
                rs=st.executeQuery("SELECT modelo,cilindrada FROM scooter WHERE id="+id);
                rs.next();
                cadena=rs.getString(1)+" "+rs.getString(2);
            }
            combo.setSelectedItem(cadena);
        } catch (SQLException ex) {
            Logger.getLogger(Reservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //obtenemos el id del elemento elegido en el combobox
    private int getId(JComboBox combo,ResultSet rs,String campo){
        int id=-1;
        String seleccion=combo.getSelectedItem().toString();
        //buscamos los nombres de producto en el resultser
        try {
            rs.beforeFirst();
            while(rs.next()){
                String currentElement;
                if(campo.equals("usuario")){
                    currentElement=rs.getString(2)+" "+rs.getString(3)+" "+rs.getString(4);
                }
                else{
                    currentElement=rs.getString(2)+" "+rs.getString(3);
                }
                
                //si coinciden, ponemos la marca
                if(seleccion.equals(currentElement)){
                    id=rs.getInt(1);
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Reservas.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    
    //lanza aviso
    private void aviso(String texto){
        Aviso aviso=new Aviso(p,true);
        aviso.setAviso(texto);
        aviso.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Reservas dialog = new Reservas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_inicio;
    private javax.swing.JComboBox<String> jComboBox_scooter;
    private javax.swing.JComboBox<String> jComboBox_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_cancel;
    private javax.swing.JLabel jLabel_ok;
    private javax.swing.JPanel jPanel_body;
    private javax.swing.JPanel jPanel_head;
    private javax.swing.JSpinner jSpinner_dia;
    private javax.swing.JSpinner jSpinner_horas;
    // End of variables declaration//GEN-END:variables

}
